/*|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Interrupt Controller

This module manages interrupt requests generated by peripherals in the MCU.

Peripherals can generate an interrupt when an event occurs that requires
attention from the CPU. Examples include a timer reaching its compare value,
GPIO detecting an event, or a communication peripheral completing an operation.

The interrupt controller records these requests, determines which interrupts
are enabled, and raises cpu_interrupt when an enabled interrupt is pending.


Interrupt Map:
    Bit 0 = Timer
    Bit 1 = GPIO
    Bit 2 = SPI
    Bit 3 = I2C
    Bit 4 = UART


Design Choices:
1. Sticky Pending Bits
   Once an interrupt occurs, its pending bit remains set until the CPU clears it.
   This prevents short interrupt events from being missed.

2. Disabled Interrupts Still Recorded
   Interrupt events set their pending bits even when disabled.
   The enable register only determines whether the event is allowed to interrupt the CPU.

3. Level Sensitive Interrupt Inputs
   A peripheral interrupt is considered active whenever its interrupt signal is high. 
   If the source remains high after being cleared, it becomes pending again.

4. New Interrupt Wins Over Clear
   If an interrupt is cleared on the same clock that a new request occurs, the interrupt remains pending so that a new event cannot be lost.

5. 1 to Clear
   Writing a 1 to a bit in INTERRUPT_CLEAR clears that pending interrupt.
   This allows individual interrupts to be cleared without affecting others.

6. Fixed Interrupt Priority
   If multiple interrupts are active, priority is:
   Timer > GPIO > SPI > I2C > UART (To be changed based on application)

7. Interrupt ID
   The controller outputs the ID of the highest priority enabled pending allowing the CPU can quickly determine which source to  service.

8. No Global Interrupt Enable
   Individual interrupt enables are controlled here. 

Register Map:

    0x0 = INTERRUPT_ENABLE
          Bit 0 = Timer interrupt enable
          Bit 1 = GPIO interrupt enable
          Bit 2 = SPI interrupt enable
          Bit 3 = I2C interrupt enable
          Bit 4 = UART interrupt enable

    0x4 = INTERRUPT_PENDING
          Bit 0 = Timer interrupt pending
          Bit 1 = GPIO interrupt pending
          Bit 2 = SPI interrupt pending
          Bit 3 = I2C interrupt pending
          Bit 4 = UART interrupt pending

    0x8 = INTERRUPT_CLEAR
          Writing a 1 to a bit clears the corresponding pending interrupt.

|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/


module interrupt_controller (
    input logic clk,
    input logic reset,
    input logic [31:0] address,
    input logic [31:0] write_data,
    input logic write_enable,
    output logic [31:0] read_data,

    // Interrupt requests from peripherals
    input logic timer_interrupt,
    input logic gpio_interrupt,
    input logic spi_interrupt,
    input logic i2c_interrupt,
    input logic uart_interrupt,


    // Interrupt request sent to CPU
    output logic cpu_interrupt,

    // ID of interrupt (highest priority)
    output logic [2:0] interrupt_id
);


// Interrupt regs
logic [4:0] interrupt_enable;
logic [4:0] interrupt_pending;

// Current periferals being requested 
logic [4:0] interrupt_requests;

// What CPU wants to clear
logic [4:0] interrupt_clear_mask;

// What interrupts qualify to reach the CPU
logic [4:0] enabled_pending_interrupts;


/****************************************************************
Interrupt Request Mapping

Each peripheral is assigned to a corresponding bit.
******************************************************************/

always_comb begin
    // Combine the individual wires into one wire
    interrupt_requests = 5'b0;
    interrupt_requests[0] = timer_interrupt;
    interrupt_requests[1] = gpio_interrupt;
    interrupt_requests[2] = spi_interrupt;
    interrupt_requests[3] = i2c_interrupt;
    interrupt_requests[4] = uart_interrupt;
end



/****************************************************************************************************************
Interrupt Clear Mask

Normally no pending interrupts are cleared

If the CPU writes to INTERRUPT_CLEAR, each written 1 indicates a pending interrupt to be cleared
******************************************************************************************************************/

always_comb begin

    interrupt_clear_mask = 5'b0;

    if (write_enable && address[3:0] == 4'b1000) begin
    interrupt_clear_mask = write_data[4:0];
    end

end



/**************************************************************************
Interrupt Pending Logic

Sticky pending bits

The current pending value is first cleared using the clear mask

Any interrupt request occurring during the same clock is then ORed
back into the pending register.

This means a new interrupt request always wins over a CPU clear.
*************************************************************************/

always_ff @(posedge clk) begin

    if (reset) begin
        interrupt_pending <= 5'b0;
    end


    else begin
// Keep the old pending bits except the ones the CPU is clearing
        interrupt_pending <= ((interrupt_pending & ~interrupt_clear_mask) | interrupt_requests);

    end

end


/**********************************************************************
Interrupt Enable Register

The CPU controls which pending interrupts are allowed to interrupt it

An interrupt can still become pending while disabled.
***********************************************************************/

always_ff @(posedge clk) begin

    if (reset) begin
        interrupt_enable <= 5'b0;
    end

    else begin
        // If we are writing to 0x0 = INTERRUPT_ENABLE
        // Then we set the write data to whatever interrupts are allowed through
        if (write_enable && address[3:0] == 4'b0000) begin 
            interrupt_enable <= write_data[4:0];
         end
    end

end


/***************************************
Enabled Pending Interrupts

Only interrupts that are both:
    1. Pending
    2. Enabled

can request CPU attention.
***************************************/

always_comb begin

    enabled_pending_interrupts = interrupt_pending & interrupt_enable;

end


/***************************************************************************
CPU Interrupt

cpu_interrupt becomes high when at least one enabled interrupt is pending
***************************************************************************/

always_comb begin

    // In default mode the CPU is not being interrupted
    cpu_interrupt = 1'b0;

    // If any of these five bits are a 1 then busy
    if (enabled_pending_interrupts != 5'b0) begin
        cpu_interrupt = 1'b1;
    end

end



/*********************************************************************
Interrupt Priority Encoder

If several interrupts are pending  the controller selects the ighest priority

Priority:
    1. Timer
    2. GPIO
    3. SPI
    4. I2C
    5. UART

interrupt_id:
    0 = Timer
    1 = GPIO
    2 = SPI
    3 = I2C
    4 = UART
***********************************************************************/

always_comb begin

    interrupt_id = 3'b000;

    // Timer (Highest priority )
    if (enabled_pending_interrupts[0]) begin
        interrupt_id = 3'd0;
    end

    // GPIO (Second Highest)
    else if (enabled_pending_interrupts[1]) begin
        interrupt_id = 3'd1;
    end

    // SPI (Third Highest)
    else if (enabled_pending_interrupts[2]) begin
        interrupt_id = 3'd2;
    end

    // I2C (Forth Highest)
    else if (enabled_pending_interrupts[3]) begin
        interrupt_id = 3'd3;
    end

    // UART (Lowest priority)  
    else if (enabled_pending_interrupts[4]) begin
        interrupt_id = 3'd4;
    end

end



/***************
CPU Read Logic
**************/

always_comb begin

    read_data = 32'b0;

    // INTERRUPT_ENABLE
    if (address[3:0] == 4'b0000) begin
        read_data[4:0] = interrupt_enable;
    end


    // INTERRUPT_PENDING
    else if (address[3:0] == 4'b0100) begin
        read_data[4:0] = interrupt_pending;
    end

end


endmodule