/*

Memory Interconnect

This module connects the CPU data interface to the different memory
devices in the MCU.

It examines the address generated by the CPU and determines which device
should receive the operation
*/

module memory_interconnect (

    // CPU side
    input  logic [31:0] cpu_address,
    input  logic [31:0] cpu_write_data,
    input  logic cpu_write_enable,
    output logic [31:0] cpu_read_data,

    // Timer
    output logic timer_write_enable,
    input logic [31:0] timer_read_data,
    // Data memory 
    output logic [31:0] memory_address,
    output logic [31:0] memory_write_data,
    output logic memory_write_enable,
    input  logic [31:0] memory_read_data,
    // UART
    output logic uart_write_enable,
    input logic [31:0] uart_read_data,
        // GPIO
    output logic gpio_write_enable,
    input logic [31:0] gpio_read_data,
    // SPI
    output logic spi_write_enable,
    input logic [31:0] spi_read_data,
    // I2C
    output logic i2c_write_enable,
    input logic [31:0] i2c_read_data,
    // Interrupt Controller
    output logic interrupt_write_enable,
    input logic [31:0] interrupt_read_data
    
);

always_comb begin

    // Default values
    cpu_read_data = 32'b0;
    memory_address = cpu_address;
    memory_write_data = cpu_write_data;
    memory_write_enable = 1'b0;
    gpio_write_enable = 1'b0; 
    uart_write_enable = 1'b0;
    spi_write_enable = 1'b0;
    i2c_write_enable = 1'b0;
    timer_write_enable = 1'b0;
    interrupt_write_enable = 1'b0;
 
    // Data memory address range
    if (cpu_address >= 32'h0000_0000 && cpu_address <= 32'h0000_07FF) begin

        memory_write_enable = cpu_write_enable;
        cpu_read_data = memory_read_data;
    end



    // GPIO address range
    else if (cpu_address >= 32'h1000_0000 && cpu_address <= 32'h1000_0FFF) begin
        gpio_write_enable = cpu_write_enable;
        cpu_read_data = gpio_read_data;
    end

    // UART address range
    else if (cpu_address >= 32'h1000_1000 && cpu_address <= 32'h1000_1FFF) begin
        uart_write_enable = cpu_write_enable;
        cpu_read_data = uart_read_data;

    end

    // SPI address range
    else if (cpu_address >= 32'h1000_2000 && cpu_address <= 32'h1000_2FFF) begin
    spi_write_enable = cpu_write_enable;
    cpu_read_data = spi_read_data;
    end
    

    // I2C address range
    else if (cpu_address >= 32'h1000_3000 && cpu_address <= 32'h1000_3FFF) begin

        i2c_write_enable = cpu_write_enable;
        cpu_read_data = i2c_read_data;

    end

    // Timer address range
    else if (cpu_address >= 32'h1000_4000 && cpu_address <= 32'h1000_4FFF) begin

        timer_write_enable = cpu_write_enable;
        cpu_read_data = timer_read_data;

    end

    // Interrupt Controller address range
    else if (cpu_address >= 32'h1000_5000 && cpu_address <= 32'h1000_5FFF) begin

        interrupt_write_enable = cpu_write_enable;
        cpu_read_data = interrupt_read_data;

    end

end

endmodule